# Generated by Django 6.1.1 on 2026-09-17 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialestado',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='solicitudes.solicitud'),
        ),
        migrations.AddField(
            model_name='documento',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='solicitudes.solicitud'),
        ),
        migrations.AlterUniqueTogether(
            name='solicitud',
            unique_together={('estudiante', 'convocatoria')},
        ),
    ]
