# Generated by Django 6.1.1 on 2026-09-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_cui_usuario_direccion_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cui',
        ),
        migrations.AddField(
            model_name='usuario',
            name='dpi',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='DPI'),
        ),
    ]
