# Generated by Django 6.1.1 on 2026-09-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='cupo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
